
CREATE DATABASE IF NOT EXISTS `competency`;
CREATE DATABASE IF NOT EXISTS `sfia`;
CREATE DATABASE IF NOT EXISTS `TPQI_DB`;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin123';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
