export const COLOR_SCHEMES = {
  skills: {
    gradient: "bg-gradient-to-b from-green-50 via-white to-green-25",
    border: "border-green-100",
    accent: "text-green-600",
    decorative: ["bg-green-200", "bg-green-300"],
    overviewBg: "bg-green-50",
    overviewBorder: "border-l-4 border-green-400",
    overviewText: "text-green-700",
    itemBorder: "border-green-200",
    itemShadow: "0 6px 18px rgba(34,197,94,0.12)",
    itemAccent: "text-green-500",
    itemDecorativeDot: "bg-green-400",
    itemText: "text-green-600",
    itemBorderClass: "border-green-300",
  },
  knowledge: {
    gradient: "bg-gradient-to-b from-purple-50 via-white to-purple-25",
    border: "border-purple-100",
    accent: "text-purple-600",
    decorative: ["bg-purple-200", "bg-purple-300"],
    overviewBg: "bg-purple-50",
    overviewBorder: "border-l-4 border-purple-400",
    overviewText: "text-purple-700",
    itemBorder: "border-purple-200",
    itemShadow: "0 6px 18px rgba(168,85,247,0.12)",
    itemAccent: "text-purple-500",
    itemDecorativeDot: "bg-purple-400",
    itemText: "text-purple-600",
    itemBorderClass: "border-purple-300",
  },
  occupational: {
    gradient: "bg-gradient-to-b from-indigo-50 via-white to-indigo-25",
    border: "border-indigo-100",
    accent: "text-indigo-600",
    decorative: ["bg-indigo-200", "bg-indigo-300"],
    overviewBg: "bg-indigo-50",
    overviewBorder: "border-l-4 border-indigo-400",
    overviewText: "text-indigo-700",
    itemBorder: "border-indigo-200",
    itemShadow: "0 6px 18px rgba(99,102,241,0.12)",
    itemAccent: "text-indigo-500",
    itemDecorativeDot: "bg-indigo-400",
    itemText: "text-indigo-600",
    itemBorderClass: "border-indigo-300",
  },
} as const;
